/* THIS FILE WAS GENERATED AUTOMATICALLY BY PAYLOAD. */
/* DO NOT MODIFY IT BECAUSE IT COULD BE REWRITTEN AT ANY TIME. */

import config from "@payload-config";
import { generatePageMetadata, NotFoundPage } from "@payloadcms/next/views";
// @ts-expect-error : This file is generated by Payload and the import map is generated in a way that TypeScript can't statically analyze it. The import map is used to dynamically import components based on the route segments, so it can't be typed in a way that satisfies TypeScript's static analysis. However, we can ignore the error here because we know that the import map will be correctly generated at runtime.
import { importMap } from "../importMap";

type Args = {
  params: Promise<{
    segments: string[];
  }>;
  searchParams: Promise<{
    [key: string]: string | string[];
  }>;
};

export const generateMetadata = ({ params, searchParams }: Args) =>
  generatePageMetadata({ config, params, searchParams });

const NotFound = ({ params, searchParams }: Args) =>
  NotFoundPage({ config, importMap, params, searchParams });

export default NotFound;
